Algoritmo "exercicio_pagamento"


Var


  nome_func : caractere
  valor_hora, qtde_horas_trab, valor_pagar : real



Inicio

 escreva("Qual o seu nome? ")
 leia(nome_func)

 escreva("Quantas horas trabalhou nesta semana?")
 leia(qtde_horas_trab)

 valor_hora <- 20.00
 
 valor_pagar <- qtde_horas_trab * valor_hora
 
 escreval("o funcionario: ", nome_func, " trabalhou ",qtde_horas_trab, " horas nessa semana e vai receber um valor de: ", valor_pagar  )
 
 
 
 
 

Fimalgoritmo