Algoritmo "exercicio_bases"


Var

a, b, c, quadrado, triangulo, trapezio: real




Inicio

escreva("qual o valor da base A? ")
leia(a)
escreva("qual o valor da base B? ")
leia(b)
escreva("qual o valor da base C? ")   '
leia(c)

quadrado <- exp(a,2)
triangulo <- (a * b) / 2
trapezio <- ((a + b) * c) / 2



escreval("area do quadrado: ", quadrado:8:4 )
escreval("area do triangulo: ", triangulo:8:4 )
escreval("area do trapezio: ", trapezio:8:4 )


Fimalgoritmo