Algoritmo "teste_saida"

Var

   a : inteiro
   b : real
   c : caractere
   d : logico

Inicio

      a <- 32
      b <- 2.34567
      c <- "Ola mundo"
      d <- VERDADEIRO
      
      escreval(a)
      escreval(b)
      escreval(c)
      escreval(d)
      escreval(b:10) //Adiciona 10 espaçoes antes do valor
      escreval(b:10:2) // Adiciona 10 espaçoes antes do valor e coloca apenas
      // duas casas decimais
Fimalgoritmo